# Generated by Django 4.0.4 on 2022-07-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fullname', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=10)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_password', models.CharField(max_length=20)),
                ('user_role', models.BooleanField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
